import { Router } from 'express'; import { Role } from '@prisma/client'; import { z } from 'zod'; import { prisma } from '../../db.js'; import { asyncHandler } from '../../lib/async.js'; import { authenticate,authorize } from '../../middleware/auth.js'; import { rankTeams,proposeBestDispatch } from './dispatch.service.js'; import { audit } from '../../lib/audit.js'; import { AppError } from '../../lib/errors.js'; import { emitOps } from '../../realtime.js';
const router=Router();router.use(authenticate);
router.get('/rank/:incidentId',asyncHandler(async(req,res)=>res.json(await rankTeams(req.params.incidentId))));
router.post('/auto/:incidentId',authorize(Role.ADMIN,Role.COMMANDER,Role.DISPATCHER),asyncHandler(async(req,res)=>{const row=await proposeBestDispatch(req.params.incidentId);await audit(req,'AUTO_PROPOSE','Dispatch',row.id,undefined,row);emitOps('dispatch.proposed',row);res.status(201).json(row)}));
router.post('/manual/:incidentId',authorize(Role.ADMIN,Role.COMMANDER,Role.DISPATCHER),asyncHandler(async(req,res)=>{const p=z.object({teamId:z.string()}).parse(req.body);const incident=await prisma.incident.findUnique({where:{id:req.params.incidentId}});const team=await prisma.team.findUnique({where:{id:p.teamId}});if(!incident||!team)throw new AppError(404,'Incident or team not found');const ranked=await rankTeams(incident.id);const candidate=ranked.find(x=>x.team.id===team.id);const row=await prisma.dispatch.create({data:{incidentId:incident.id,teamId:team.id,score:candidate?.score||0,distanceKm:candidate?.distanceKm||0,etaMinutes:candidate?.etaMinutes||15,explanation:candidate?.explanation||{manual:true,reason:'Operator override'}}});await audit(req,'MANUAL_PROPOSE','Dispatch',row.id,undefined,row);emitOps('dispatch.proposed',row);res.status(201).json(row)}));
router.post('/:id/accept',authorize(Role.ADMIN,Role.COMMANDER,Role.DISPATCHER,Role.SUPERVISOR),asyncHandler(async(req,res)=>{const d=await prisma.dispatch.findUnique({where:{id:req.params.id},include:{incident:true}});if(!d)throw new AppError(404,'Dispatch not found');const resourceIds=z.object({resourceIds:z.array(z.string()).default([])}).parse(req.body).resourceIds;const row=await prisma.$transaction(async tx=>{await tx.dispatchResource.createMany({data:resourceIds.map(resourceId=>({dispatchId:d.id,resourceId})),skipDuplicates:true});await tx.team.update({where:{id:d.teamId},data:{status:'BUSY',activeJobs:{increment:1}}});if(resourceIds.length)await tx.resource.updateMany({where:{id:{in:resourceIds}},data:{status:'IN_USE'}});await tx.incident.update({where:{id:d.incidentId},data:{status:'ASSIGNED'}});await tx.incidentStatusEvent.create({data:{incidentId:d.incidentId,fromStatus:d.incident.status,toStatus:'ASSIGNED',actorId:req.user!.id,note:'Dispatch accepted'}});return tx.dispatch.update({where:{id:d.id},data:{status:'ACCEPTED',acceptedAt:new Date()}})});await audit(req,'ACCEPT','Dispatch',row.id,d,row);emitOps('dispatch.accepted',row);res.json(row)}));
router.post('/:id/complete',authorize(Role.ADMIN,Role.COMMANDER,Role.DISPATCHER,Role.SUPERVISOR,Role.TECHNICIAN),asyncHandler(async(req,res)=>{const d=await prisma.dispatch.findUnique({where:{id:req.params.id},include:{resources:true}});if(!d)throw new AppError(404,'Dispatch not found');const row=await prisma.$transaction(async tx=>{await tx.team.update({where:{id:d.teamId},data:{activeJobs:{decrement:1},status:'AVAILABLE'}});const rids=d.resources.map(x=>x.resourceId);if(rids.length)await tx.resource.updateMany({where:{id:{in:rids}},data:{status:'AVAILABLE'}});return tx.dispatch.update({where:{id:d.id},data:{status:'COMPLETED',completedAt:new Date()}})});emitOps('dispatch.completed',row);res.json(row)}));

router.patch('/:id/state',authorize(Role.ADMIN,Role.COMMANDER,Role.DISPATCHER,Role.SUPERVISOR,Role.TECHNICIAN),asyncHandler(async(req,res)=>{const p=z.object({status:z.enum(['DISPATCHED','ARRIVED','CANCELLED'])}).parse(req.body);const d=await prisma.dispatch.findUnique({where:{id:req.params.id},include:{incident:true}});if(!d)throw new AppError(404,'Dispatch not found');const data:any={status:p.status};if(p.status==='DISPATCHED')data.dispatchedAt=new Date();if(p.status==='ARRIVED')data.arrivedAt=new Date();const incidentStatus=p.status==='DISPATCHED'?'EN_ROUTE':p.status==='ARRIVED'?'ON_SITE':d.incident.status;const row=await prisma.$transaction(async tx=>{const out=await tx.dispatch.update({where:{id:d.id},data});if(p.status!=='CANCELLED'){await tx.incident.update({where:{id:d.incidentId},data:{status:incidentStatus as any}});await tx.incidentStatusEvent.create({data:{incidentId:d.incidentId,fromStatus:d.incident.status,toStatus:incidentStatus as any,actorId:req.user!.id,note:`Dispatch ${p.status.toLowerCase()}`}});}return out});emitOps('dispatch.updated',row);res.json(row)}));
export default router;
