import { PrismaClient, Role } from '@prisma/client';import bcrypt from 'bcryptjs';const p=new PrismaClient();
async function main(){
 await p.dispatchResource.deleteMany();await p.dispatch.deleteMany();await p.incidentStatusEvent.deleteMany();await p.incident.deleteMany();await p.teamMember.deleteMany();await p.team.deleteMany();await p.resource.deleteMany();await p.inventoryTransaction.deleteMany();await p.inventoryItem.deleteMany();await p.zone.deleteMany();await p.site.deleteMany();await p.notification.deleteMany();await p.auditLog.deleteMany();await p.user.deleteMany();
 const passwordHash=await bcrypt.hash('Madad@123',10);
 const [admin,commander,dispatcher,tech]=await Promise.all([
  p.user.create({data:{email:'admin@madad.sa',name:'System Admin',role:Role.ADMIN,passwordHash}}),p.user.create({data:{email:'commander@madad.sa',name:'Operations Commander',role:Role.COMMANDER,passwordHash}}),p.user.create({data:{email:'dispatcher@madad.sa',name:'Dispatcher',role:Role.DISPATCHER,passwordHash}}),p.user.create({data:{email:'tech@madad.sa',name:'Field Technician',role:Role.TECHNICIAN,passwordHash}})
 ]);
 const mina=await p.site.create({data:{code:'MINA',name:'Mina',latitude:21.4133,longitude:39.8931}});const arafat=await p.site.create({data:{code:'ARAFAT',name:'Arafat',latitude:21.3549,longitude:39.9842}});
 const z1=await p.zone.create({data:{code:'MINA-A',name:'Mina Zone A',siteId:mina.id,latitude:21.4150,longitude:39.8950}});const z2=await p.zone.create({data:{code:'MINA-B',name:'Mina Zone B',siteId:mina.id,latitude:21.4095,longitude:39.8895}});const z3=await p.zone.create({data:{code:'ARA-A',name:'Arafat Zone A',siteId:arafat.id,latitude:21.356,longitude:39.982}});
 const electrical=await p.team.create({data:{code:'T-ELEC-01',name:'Electrical Response 1',specialization:'ELECTRICAL',skills:['power','generator','distribution'],siteId:mina.id,zoneId:z1.id,latitude:21.4144,longitude:39.8943,maxConcurrentJobs:2}});const utilities=await p.team.create({data:{code:'T-UTIL-01',name:'Utilities Team 1',specialization:'UTILITIES',skills:['pump','water','generator'],siteId:mina.id,zoneId:z2.id,latitude:21.4100,longitude:39.8902,maxConcurrentJobs:2}});await p.team.create({data:{code:'T-ELEC-02',name:'Electrical Response 2',specialization:'ELECTRICAL',skills:['power','switchgear'],siteId:arafat.id,zoneId:z3.id,latitude:21.3555,longitude:39.9828,maxConcurrentJobs:2}});
 await p.teamMember.createMany({data:[{teamId:electrical.id,userId:tech.id},{teamId:utilities.id,userId:dispatcher.id}]});
 await p.resource.createMany({data:[{assetTag:'GEN-001',name:'Mobile Generator 1',type:'GENERATOR',siteId:mina.id,latitude:21.413,longitude:39.893,capabilities:['power']},{assetTag:'PMP-001',name:'Mobile Water Pump',type:'PUMP',siteId:mina.id,latitude:21.410,longitude:39.890,capabilities:['water','pump']},{assetTag:'VEH-001',name:'Field Vehicle 1',type:'VEHICLE',siteId:mina.id,latitude:21.412,longitude:39.892,capabilities:['transport']} ]});
 await p.inventoryItem.createMany({data:[{sku:'FUSE-250',name:'250A Fuse',quantity:16,reorderLevel:5,unit:'pcs'},{sku:'PUMP-SEAL',name:'Pump Seal Kit',quantity:6,reorderLevel:3,unit:'kit'},{sku:'CABLE-50',name:'50mm Power Cable',quantity:120,reorderLevel:40,unit:'m'}]});
 const i1=await p.incident.create({data:{code:'INC-DEMO-001',title:'Electrical distribution outage',description:'Distribution panel lost power in Mina Zone A',category:'ELECTRICAL',requiredSkills:['power','distribution'],severity:'CRITICAL',siteId:mina.id,zoneId:z1.id,latitude:21.4160,longitude:39.8960,slaMinutes:20}});const i2=await p.incident.create({data:{code:'INC-DEMO-002',title:'Water pump pressure failure',description:'Primary pump pressure dropped below operating range',category:'UTILITIES',requiredSkills:['pump','water'],severity:'HIGH',siteId:mina.id,zoneId:z2.id,latitude:21.4090,longitude:39.8885,slaMinutes:30}});
 await p.incidentStatusEvent.createMany({data:[{incidentId:i1.id,toStatus:'OPEN',actorId:commander.id,note:'Demo incident'},{incidentId:i2.id,toStatus:'OPEN',actorId:commander.id,note:'Demo incident'}]});
 console.log('Seeded MADAD demo data', {admin:admin.email});
}
main().finally(()=>p.$disconnect());
