import { Router } from 'express'; import { Role, TeamStatus, ResourceStatus, ResourceType, InventoryTxnType } from '@prisma/client'; import { z } from 'zod'; import { prisma } from '../../db.js'; import { authenticate,authorize } from '../../middleware/auth.js'; import { asyncHandler } from '../../lib/async.js'; import { AppError } from '../../lib/errors.js';
const r=Router();r.use(authenticate);
r.get('/sites',asyncHandler(async(_q,res)=>res.json(await prisma.site.findMany({include:{zones:true}}))));
r.get('/teams',asyncHandler(async(_q,res)=>res.json(await prisma.team.findMany({include:{site:true,zone:true,members:{include:{user:{select:{id:true,name:true,role:true}}}}},orderBy:{name:'asc'}}))));
r.post('/teams',authorize(Role.ADMIN,Role.COMMANDER),asyncHandler(async(req,res)=>{const p=z.object({code:z.string(),name:z.string(),specialization:z.string(),siteId:z.string(),zoneId:z.string().nullable().optional(),latitude:z.number(),longitude:z.number(),maxConcurrentJobs:z.number().int().min(1).default(2),skills:z.array(z.string()).default([])}).parse(req.body);res.status(201).json(await prisma.team.create({data:p}))}));
r.patch('/teams/:id/status',authorize(Role.ADMIN,Role.COMMANDER,Role.DISPATCHER,Role.SUPERVISOR),asyncHandler(async(req,res)=>{const status=z.object({status:z.nativeEnum(TeamStatus)}).parse(req.body).status;res.json(await prisma.team.update({where:{id:req.params.id},data:{status}}))}));
r.get('/resources',asyncHandler(async(_q,res)=>res.json(await prisma.resource.findMany({include:{site:true},orderBy:{name:'asc'}}))));
r.post('/resources',authorize(Role.ADMIN,Role.COMMANDER),asyncHandler(async(req,res)=>{const p=z.object({assetTag:z.string(),name:z.string(),type:z.nativeEnum(ResourceType),siteId:z.string(),latitude:z.number().optional(),longitude:z.number().optional(),capabilities:z.array(z.string()).default([])}).parse(req.body);res.status(201).json(await prisma.resource.create({data:p}))}));
r.patch('/resources/:id/status',authorize(Role.ADMIN,Role.COMMANDER,Role.SUPERVISOR),asyncHandler(async(req,res)=>{const status=z.object({status:z.nativeEnum(ResourceStatus)}).parse(req.body).status;res.json(await prisma.resource.update({where:{id:req.params.id},data:{status}}))}));
r.get('/inventory',asyncHandler(async(_q,res)=>res.json(await prisma.inventoryItem.findMany({orderBy:{name:'asc'}}))));
r.post('/inventory/:id/transaction',authorize(Role.ADMIN,Role.COMMANDER,Role.SUPERVISOR),asyncHandler(async(req,res)=>{const p=z.object({type:z.nativeEnum(InventoryTxnType),quantity:z.number().int().positive(),reference:z.string().optional(),notes:z.string().optional()}).parse(req.body);const item=await prisma.inventoryItem.findUnique({where:{id:req.params.id}});if(!item)throw new AppError(404,'Inventory item not found');const delta=['RECEIPT','RETURN'].includes(p.type)?p.quantity:-p.quantity;if(item.quantity+delta<0)throw new AppError(409,'Insufficient stock');const out=await prisma.$transaction([prisma.inventoryTransaction.create({data:{itemId:item.id,...p}}),prisma.inventoryItem.update({where:{id:item.id},data:{quantity:{increment:delta}}})]);res.status(201).json(out[1])}));
r.get('/notifications',asyncHandler(async(req,res)=>res.json(await prisma.notification.findMany({where:{userId:req.user!.id},orderBy:{createdAt:'desc'},take:50}))));
r.get('/audit',authorize(Role.ADMIN,Role.COMMANDER),asyncHandler(async(_q,res)=>res.json(await prisma.auditLog.findMany({include:{actor:{select:{name:true,email:true}}},orderBy:{createdAt:'desc'},take:200}))));

r.get('/users',authorize(Role.ADMIN,Role.COMMANDER),asyncHandler(async(_q,res)=>res.json(await prisma.user.findMany({select:{id:true,email:true,name:true,role:true,phone:true,isActive:true,createdAt:true},orderBy:{name:'asc'}}))));
r.patch('/notifications/:id/read',asyncHandler(async(req,res)=>{const out=await prisma.notification.updateMany({where:{id:req.params.id,userId:req.user!.id},data:{isRead:true}});if(!out.count)throw new AppError(404,'Notification not found');res.json({updated:true})}));
export default r;
