import { PrismaClient,IncidentSeverity,IncidentStatus,TeamStatus,ResourceStatus,ResourceType,Role } from '@prisma/client'; import bcrypt from 'bcryptjs';
const p=new PrismaClient(); const passwordHash=await bcrypt.hash('Madad@123',12);
async function main(){
 await p.dispatchResource.deleteMany();await p.dispatch.deleteMany();await p.incidentStatusEvent.deleteMany();await p.incident.deleteMany();await p.teamMember.deleteMany();await p.team.deleteMany();await p.resource.deleteMany();await p.inventoryTransaction.deleteMany();await p.inventoryItem.deleteMany();await p.zone.deleteMany();await p.site.deleteMany();await p.notification.deleteMany();await p.auditLog.deleteMany();await p.refreshToken.deleteMany();await p.user.deleteMany();
 const users=await Promise.all([
  ['admin@madad.sa','System Admin',Role.ADMIN],['commander@madad.sa','Operations Commander',Role.COMMANDER],['dispatcher@madad.sa','Dispatch Officer',Role.DISPATCHER],['supervisor@madad.sa','Field Supervisor',Role.SUPERVISOR],['tech1@madad.sa','Field Technician 1',Role.TECHNICIAN],['tech2@madad.sa','Field Technician 2',Role.TECHNICIAN],['tech3@madad.sa','Electrical Technician',Role.TECHNICIAN]
 ].map(([email,name,role])=>p.user.create({data:{email:email as string,name:name as string,role:role as Role,passwordHash}})));
 const siteData=[
  {code:'MINA',nameAr:'منى',nameEn:'Mina',latitude:21.4133,longitude:39.8933,criticality:5,zones:[['M-A','Mina A',5,21.4140,39.8910],['M-B','Mina B',4,21.4120,39.8960],['M-C','Mina C',3,21.4160,39.8990]]},
  {code:'ARAFA',nameAr:'عرفات',nameEn:'Arafat',latitude:21.3548,longitude:39.9841,criticality:5,zones:[['A-A','Arafat A',5,21.355,39.981],['A-B','Arafat B',4,21.352,39.987]]},
  {code:'MUZ',nameAr:'مزدلفة',nameEn:'Muzdalifah',latitude:21.3891,longitude:39.9128,criticality:4,zones:[['Z-A','Muzdalifah A',4,21.390,39.911],['Z-B','Muzdalifah B',3,21.387,39.915]]}
 ];
 const sites:any[]=[];for(const s of siteData){const site=await p.site.create({data:{code:s.code,nameAr:s.nameAr,nameEn:s.nameEn,latitude:s.latitude,longitude:s.longitude,criticality:s.criticality}});const zones=[];for(const z of s.zones){zones.push(await p.zone.create({data:{code:z[0] as string,name:z[1] as string,crowdDensity:z[2] as number,latitude:z[3] as number,longitude:z[4] as number,siteId:site.id}}))}sites.push({...site,zones})}
 const teamSpecs=[['T-M-01','Mina Rapid Response','General Operations',0,0,['general','safety','crowd']],['T-M-02','Mina Electrical','Electrical',0,1,['electrical','generator','lighting']],['T-A-01','Arafat Safety','Safety',1,0,['safety','fire','crowd']],['T-A-02','Arafat Facilities','Facilities',1,1,['plumbing','hvac','general']],['T-Z-01','Muzdalifah Mobile','Mobile Support',2,0,['general','electrical','safety']]];
 const teams=[];for(let i=0;i<teamSpecs.length;i++){const [code,name,spec,si,zi,skills]=teamSpecs[i] as any[];const site=sites[si],zone=site.zones[zi];teams.push(await p.team.create({data:{code,name,specialization:spec,status:i===3?TeamStatus.BUSY:TeamStatus.AVAILABLE,siteId:site.id,zoneId:zone.id,latitude:zone.latitude+.001,longitude:zone.longitude+.001,activeJobs:i===3?1:0,maxConcurrentJobs:2,skills}}))}
 await p.teamMember.createMany({data:[{teamId:teams[0].id,userId:users[4].id,isLead:true},{teamId:teams[1].id,userId:users[6].id,isLead:true},{teamId:teams[2].id,userId:users[5].id,isLead:true}]});
 for(let i=1;i<=18;i++){const site=sites[i%3];await p.resource.create({data:{assetTag:`AST-${String(i).padStart(4,'0')}`,name:i%3===0?`Utility Vehicle ${i}`:i%3===1?`Portable Generator ${i}`:`Safety Kit ${i}`,type:i%3===0?ResourceType.VEHICLE:i%3===1?ResourceType.EQUIPMENT:ResourceType.SAFETY_KIT,status:i===7?ResourceStatus.MAINTENANCE:ResourceStatus.AVAILABLE,siteId:site.id,latitude:site.latitude,longitude:site.longitude,capabilities:i%3===1?['power','generator']:i%3===0?['transport','mobile']:['safety','first-response'],lastInspectionAt:new Date(Date.now()-10*86400e3),nextInspectionAt:new Date(Date.now()+20*86400e3)}})}
 for(const x of [['SP-001','Generator Belt','Mechanical','pcs',18,6,'Mina Store A'],['SP-002','LED Floodlight','Electrical','pcs',7,8,'Mina Store B'],['SP-003','Water Pump Hose','Facilities','pcs',12,5,'Arafat Store'],['SP-004','Safety Barrier','Safety','pcs',40,15,'Central Store'],['SP-005','Radio Battery','Communications','pcs',6,10,'Central Store']])await p.inventoryItem.create({data:{sku:x[0] as string,name:x[1] as string,category:x[2] as string,unit:x[3] as string,quantity:x[4] as number,reorderLevel:x[5] as number,storageLocation:x[6] as string}});
 const cats=['Electrical','Facilities','Crowd','Safety','Water','Transport'];const titles=['Lighting outage near service corridor','Water leakage at field station','Crowd barrier displaced','Generator overheating alert','Blocked service access route','Communication point power loss','Cooling unit failure','Damaged directional sign'];
 for(let i=0;i<28;i++){const site=sites[i%3],zone=site.zones[i%site.zones.length];const severity=[IncidentSeverity.LOW,IncidentSeverity.MEDIUM,IncidentSeverity.HIGH,IncidentSeverity.CRITICAL][i%4];const status=[IncidentStatus.NEW,IncidentStatus.TRIAGED,IncidentStatus.ASSIGNED,IncidentStatus.EN_ROUTE,IncidentStatus.ON_SITE,IncidentStatus.RESOLVED][i%6];const reportedAt=new Date(Date.now()-(i*47+12)*60000);const resolved=status===IncidentStatus.RESOLVED?new Date(reportedAt.getTime()+(25+i%5*10)*60000):null;await p.incident.create({data:{reference:`INC-2026-${String(i+1).padStart(5,'0')}`,title:titles[i%titles.length],description:`Synthetic operational incident ${i+1} used for MADAD demonstration and workflow testing.`,category:cats[i%cats.length],severity,status,siteId:site.id,zoneId:zone.id,latitude:zone.latitude+(i%3)*.0005,longitude:zone.longitude+(i%2)*.0004,reportedById:users[2].id,peopleAffected:(i%7)*6,slaMinutes:severity==='CRITICAL'?20:severity==='HIGH'?35:60,requiredSkills:[cats[i%cats.length].toLowerCase()],requiredCapabilities:i%4===0?['power']:[],aiRiskScore:.35+(i%4)*.17,aiSlaBreachProbability:.18+(i%4)*.19,aiEstimatedResolutionMinutes:25+(i%4)*15,aiSummary:'Seeded explainable AI assessment for demo data.',reportedAt,resolvedAt:resolved,statusEvents:{create:{toStatus:status,actorId:users[2].id,note:'Seeded lifecycle event'}}}})}
 await p.notification.createMany({data:[{userId:users[1].id,type:'CRITICAL',title:'Critical incident detected',message:'A critical incident requires command review.',entityType:'Incident'},{userId:users[2].id,type:'ASSIGNMENT',title:'Dispatch queue updated',message:'New incidents are waiting for team assignment.',entityType:'Dispatch'},{userId:users[0].id,type:'WARNING',title:'Low inventory',message:'Some inventory items are below reorder level.',entityType:'Inventory'}]});
 console.log('MADAD seed complete');
}
main().finally(()=>p.$disconnect());
