'use client';
import { useEffect, useState } from 'react';
import { io } from 'socket.io-client';
import AppShell from '../../components/AppShell';
import { api } from '../../lib/api';

type Overview={counters:{openIncidents:number;criticalIncidents:number;availableTeams:number;busyTeams:number;availableResources:number;lowStock:number};recentIncidents:any[]};
export default function Dashboard(){const [data,setData]=useState<Overview|null>(null);const [error,setError]=useState('');
const load=()=>api<Overview>('/operations/overview').then(setData).catch(e=>setError(e.message));
useEffect(()=>{load();const s=io(process.env.NEXT_PUBLIC_SOCKET_URL||'http://localhost:4000');['incident.created','incident.updated','dispatch.proposed','dispatch.accepted','dispatch.completed'].forEach(ev=>s.on(ev,load));return()=>{s.disconnect()}},[]);
return <AppShell><div className="topbar"><div><div className="eyebrow">OPERATIONS COMMAND CENTER</div><h1 className="title">مركز العمليات</h1><p className="subtitle">صورة تشغيلية موحدة للبلاغات والفرق والموارد.</p></div><button className="btn ghost" onClick={load}>تحديث</button></div>{error&&<div className="error">{error}</div>}<div className="grid grid-4">{[['البلاغات المفتوحة',data?.counters.openIncidents??'—'],['البلاغات الحرجة',data?.counters.criticalIncidents??'—'],['الفرق المتاحة',data?.counters.availableTeams??'—'],['الموارد المتاحة',data?.counters.availableResources??'—']].map(([l,n])=><div className="card metric" key={l}><div className="label">{l}</div><div className="num">{n}</div></div>)}</div><div className="spacer"/><div className="grid grid-2"><section className="card"><h2 className="section-title">آخر البلاغات</h2><div className="table-wrap"><table className="table"><thead><tr><th>الكود</th><th>البلاغ</th><th>الموقع</th><th>الخطورة</th><th>الحالة</th></tr></thead><tbody>{data?.recentIncidents.map(i=><tr key={i.id}><td>{i.code}</td><td>{i.title}</td><td>{i.site?.name}</td><td><span className={`badge ${String(i.severity).toLowerCase()}`}>{i.severity}</span></td><td>{i.status}</td></tr>)}</tbody></table></div></section><section className="card"><h2 className="section-title">مؤشرات جاهزية التشغيل</h2><div className="grid grid-2"><div className="metric"><div className="label">فرق مشغولة</div><div className="num">{data?.counters.busyTeams??'—'}</div></div><div className="metric"><div className="label">أصناف تحت حد إعادة الطلب</div><div className="num">{data?.counters.lowStock??'—'}</div></div></div><p className="muted">تتحدث اللوحة تلقائيًا مع أحداث البلاغ والتوجيه عبر Socket.IO.</p></section></div></AppShell>}
